CREATE TABLE USER(
	UID INTEGER PRIMARY KEY,
    FIRST_NAME VARCHAR(256),
    LAST_NAME VARCHAR(256),
    WEB_LOGIN_ID VARCHAR(100) UNIQUE NOT NULL,
    PASSWORD VARCHAR(256) NOT NULL,
    FAILED_LOGIN_ATTEMPT INTEGER,
    LAST_LOGIN_AT DATE,
    CREATED_AT DATE,
    UPDATE_AT DATE,
    CURRENT_OFFICE VARCHAR(100) NOT NULL,
    ROLE VARCHAR(100) NOT NULL,
    DELETED BOOL
);

CREATE TABLE DEMAND(
	UID INTEGER PRIMARY KEY,
    OFFICE_LOCATION VARCHAR(256) NOT NULL,
    OFFICE_ADDRESS VARCHAR(256) NOT NULL,
    DEMAND_PROFILE VARCHAR(100) NOT NULL,
    REQUIREMENTS JSON NOT NULL,
    EXPERIENCE INTEGER NOT NULL,
    TOTAL_DEMAND INTEGER NOT NULL,
    IN_PROCESS INTEGER NOT NULL,
    DELETED BOOL
);

CREATE TABLE USER_DEMAND(
	UID INTEGER PRIMARY KEY,
	USER_UID INTEGER NOT NULL,
    DEMAND_UID INTEGER NOT NULL,
    FOREIGN KEY (USER_UID) REFERENCES USER(UID),
    FOREIGN KEY (DEMAND_UID) REFERENCES DEMAND(UID)
);

CREATE TABLE USER_LOGS(
	UID INTEGER PRIMARY KEY,
    USER_UID INTEGER NOT NULL,
    DESCRIPTION VARCHAR(1000) NOT NULL,
    CREATED_AT DATE,
    DELETED BOOL,
    FOREIGN KEY (USER_UID) REFERENCES USER(UID)
);

CREATE TABLE ONBOARDEE(
	UID INTEGER PRIMARY KEY,
    FIRST_NAME VARCHAR(256),
    LAST_NAME VARCHAR(256),
    WEB_LOGIN_ID VARCHAR(100) UNIQUE NOT NULL,
    SKILLS JSON,
    EXPERIENCE INTEGER NOT NULL,
    DEMAND INTEGER,
    STATUS VARCHAR(100),
    BG_STATUS VARCHAR(100),
    ETA_FOR_ONBOARDING INTEGER,
    DELETED BOOL,
    FOREIGN KEY (DEMAND) REFERENCES USER_DEMAND(UID)
);